IncrementalAlterConfigs:
  key: 0
  version: 0
  req:
  - struct: IncrementalAlterConfigsRequest
    fields:
    - name: Resources
      type: '[]Resources'
      version: 0
    - name: ValidateOnly
      type: bool
      version: 0
    - name: TagBuffer
      type: tag_buffer
      version: 0
  - struct: Resources
    fields:
    - name: ResourceType
      type: int8
      version: 0
    - name: ResourceName
      type: compact_string
      version: 0
    - name: Configs
      type: '[]Configs'
      version: 0
  - struct: Configs
    fields:
    - name: Name
      type: compact_string
      version: 0
    - name: ConfigOperation
      type: int8
      version: 0
    - name: Value
      type: compact_nullable_string
      version: 0
    - name: TagBuffer
      type: tag_buffer
      version: 0
  res:
  - struct: IncrementalAlterConfigsResponse
    fields:
    - name: ThrottleTimeMs
      type: int32
      version: 0
    - name: Responses
      type: '[]Responses'
      version: 0
  - struct: Responses
    fields:
    - name: ErrorCode
      type: int16
      version: 0
    - name: ErrorMessage
      type: compact_nullable_string
      version: 0
    - name: ResourceType
      type: int8
      version: 0
    - name: ResourceName
      type: compact_string
      version: 0
    - name: TagBuffer
      type: tag_buffer
      version: 0
