Produce:
  key: 0
  version: 8
  req:
  - struct: ProduceRequest
    fields:
    - name: TransactionalId
      type: nullable_string
      version: 3
    - name: Acks
      type: int16
      version: 0
    - name: Timeout
      type: int32
      version: 0
    - name: TopicData
      type: '[]TopicData'
      version: 0
  - struct: TopicData
    fields:
    - name: Topic
      type: string
      version: 0
    - name: Data
      type: '[]Data'
      version: 0
  - struct: Data
    fields:
    - name: Partition
      type: int32
      version: 0
    - name: RecordSet
      type: records
      version: 0
  res:
  - struct: ProduceResponse
    fields:
    - name: Responses
      type: '[]Response'
      version: 0
    - name: ThrottleTimeMs
      type: int32
      version: 1
  - struct: Response
    fields:
    - name: Topic
      type: string
      version: 0
    - name: PartitionResponses
      type: '[]PartitionResponse'
      version: 0
  - struct: PartitionResponse
    fields:
    - name: Partition
      type: int32
      version: 0
    - name: ErrorCode
      type: int16
      version: 0
    - name: BaseOffset
      type: int64
      version: 0
    - name: LogAppendTime
      type: int64
      version: 2
    - name: LogStartOffset
      type: int64
      version: 5
    - name: RecordErrors
      type: '[]RecordError'
      version: 8
    - name: ErrorMessage
      type: nullable_string
      version: 8
  - struct: RecordError
    fields:
    - name: BatchIndex
      type: int32
      version: 8
    - name: BatchIndexErrorMessage
      type: nullable_string
      version: 8
